[package]
name = "piet-parser"
version = "0.1.0"
edition = "2021"

[lib]
name = "parser"
path = "src/lib.rs"

[dependencies]
piet-core = { version = "0.1", path = "../piet_core" }
image = "0.24.5"
gcd = "2.3.0"
rand = "0.8"