[package]
name = "piet-interpreter"
version = "0.1.0"
edition = "2021"

[lib]
name = "interpreter"
path = "src/lib.rs"

[dependencies]
image = "0.24.5"
gcd = "2.3.0"
piet-core = { version = "0.1", path = "../piet_core" }
piet-parser = { version = "0.1", path = "../parser" }